# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rps_pb2 as rps__pb2


class RockPaperScissorsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlayGame = channel.unary_unary(
                '/rock_paper_scissors.RockPaperScissors/PlayGame',
                request_serializer=rps__pb2.GameRequest.SerializeToString,
                response_deserializer=rps__pb2.GameResponse.FromString,
                )


class RockPaperScissorsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PlayGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RockPaperScissorsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlayGame': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayGame,
                    request_deserializer=rps__pb2.GameRequest.FromString,
                    response_serializer=rps__pb2.GameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rock_paper_scissors.RockPaperScissors', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RockPaperScissors(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlayGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rock_paper_scissors.RockPaperScissors/PlayGame',
            rps__pb2.GameRequest.SerializeToString,
            rps__pb2.GameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
